# Generated by Django 3.0.5 on 2020-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safariaccount',
            options={'verbose_name': 'Safari Account', 'verbose_name_plural': 'Safari Accounts'},
        ),
        migrations.AddField(
            model_name='safariaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
